<a href="https://colab.research.google.com/github/LUCY-JungHwaKim/DataAnalysis/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0%EC%8B%A4%EC%8A%B5_1110_%EC%A0%9C2%EC%9C%A0%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/AnalyticsKnight/yemoonsaBigdata

Cloning into 'yemoonsaBigdata'...
remote: Enumerating objects: 485, done.
remote: Counting objects: 100% (122/122), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 485 (delta 66), reused 49 (delta 44), pack-reused 363
Receiving objects: 100% (485/485), 8.89 MiB | 20.59 MiB/s, done.
Resolving deltas: 100% (251/251), done.


In [3]:
import pandas as pd
X_test = pd.read_csv('./yemoonsaBigdata/datasets/Part2/mpg_X_test.csv')
X_train = pd.read_csv('./yemoonsaBigdata/datasets/Part2/mpg_X_train.csv')
y_train = pd.read_csv('./yemoonsaBigdata/datasets/Part2/mpg_y_train.csv')

In [4]:
X_test.head()

name   mpg  cylinders  displacement  horsepower  weight  \
0        maxda glc deluxe  34.1          4          86.0        65.0    1975   
1        plymouth sapporo  23.2          4         156.0       105.0    2745   
2  dodge coronet brougham  16.0          8         318.0       150.0    4190   
3        amc concord dl 6  20.2          6         232.0        90.0    3265   
4      fiat strada custom  37.3          4          91.0        69.0    2130   

   acceleration  model_year  
0          15.2          79  
1          16.7          78  
2          13.0          76  
3          18.2          79  
4          14.7          79

In [5]:
## 32가지의 자동차 연료 소피를 포함한 데이터
y_train.head() ## 차량 모델의 미국산 여부
## 예측 모형을 만든 후 평가용 데이터에 적용하여 얻은 국가 예측값을 csv 파일로 생성해야함

isUSA
0      1
1      1
2      0
3      1
4      0

In [6]:
import pandas as pd
import numpy as np

X_train.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          278 non-null    object 
 1   mpg           278 non-null    float64
 2   cylinders     278 non-null    int64  
 3   displacement  278 non-null    float64
 4   horsepower    274 non-null    float64
 5   weight        278 non-null    int64  
 6   acceleration  278 non-null    float64
 7   model_year    278 non-null    int64  
dtypes: float64(4), int64(3), object(1)
memory usage: 17.5+ KB


In [7]:
## 결측치 처리
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
X_train[['horsepower']] = imputer.fit_transform(X_train[['horsepower']])

X_test[['horsepower']] = imputer.fit_transform(X_test[['horsepower']])

In [8]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          278 non-null    object 
 1   mpg           278 non-null    float64
 2   cylinders     278 non-null    int64  
 3   displacement  278 non-null    float64
 4   horsepower    278 non-null    float64
 5   weight        278 non-null    int64  
 6   acceleration  278 non-null    float64
 7   model_year    278 non-null    int64  
dtypes: float64(4), int64(3), object(1)
memory usage: 17.5+ KB


In [9]:
X_train.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  278.000000  278.000000    278.000000  278.000000   278.000000   
mean    23.732734    5.374101    189.994604  103.383212  2948.464029   
std      7.647295    1.677084    105.471423   38.695458   862.949746   
min     10.000000    3.000000     68.000000   46.000000  1613.000000   
25%     18.000000    4.000000     98.000000   75.000000  2206.250000   
50%     23.000000    4.000000    140.500000   90.500000  2737.500000   
75%     29.000000    6.000000    258.000000  118.750000  3560.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    278.000000  278.000000  
mean      15.580216   76.057554  
std        2.745907    3.605591  
min        8.000000   70.000000  
25%       14.000000   73.000000  
50%       15.500000   76.000000  
75%       17.000000   79.000000  
max       24.800000   82.000000

In [10]:
COL_DEL = ['name']
COL_NUM = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year']
COL_CAT = []
COL_Y = ['isUSA']

X_train = X_train.iloc[:, 1:]
X_test = X_test.iloc[:, 1:]

In [11]:
X_train.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  model_year
0  31.0          4         112.0        85.0    2575          16.2          82
1  13.0          8         400.0       175.0    5140          12.0          71
2  37.0          4          91.0        68.0    2025          18.2          82
3  12.0          8         350.0       180.0    4499          12.5          73
4  19.0          4         120.0        88.0    3270          21.9          76

In [13]:
## 데이터 모형 구축
from sklearn.model_selection import train_test_split

X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train , test_size=0.3)

In [14]:
## 대개의 경우 스케일링을 진행함

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_tr[COL_NUM])

X_tr[COL_NUM] = scaler.transform(X_tr[COL_NUM])
X_val[COL_NUM] = scaler.transform(X_val[COL_NUM])
X_test[COL_NUM] = scaler.transform(X_test[COL_NUM])

In [17]:
y_tr.head()

isUSA
124      0
142      1
45       1
210      0
32       1

In [16]:
## knn 사용
from sklearn.neighbors import KNeighborsClassifier

modelKNN = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
modelKNN.fit(X_tr, y_tr.values.ravel()) ## ravel : 다차원 배열을 1차원 배열로 평평하게 만들어 주는 것

KNeighborsClassifier(metric='euclidean')

In [18]:
## DT 사용
from sklearn.tree import DecisionTreeClassifier

modelDT = DecisionTreeClassifier(max_depth=10)
modelDT.fit(X_tr, y_tr)

DecisionTreeClassifier(max_depth=10)

In [19]:
## 데이터 모형 평가

y_val_pred_probaKNN = modelKNN.predict_proba(X_val)
y_val_pred_probaDT = modelDT.predict_proba(X_val)

In [22]:
y_val_pred_probaKNN

array([[1. , 0. ],
       [0. , 1. ],
       [0.8, 0.2],
       [0.8, 0.2],
       [0. , 1. ],
       [0.8, 0.2],
       [0.6, 0.4],
       [0.8, 0.2],
       [1. , 0. ],
       [0.6, 0.4],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0.8, 0.2],
       [0. , 1. ],
       [0.8, 0.2],
       [0. , 1. ],
       [0.6, 0.4],
       [1. , 0. ],
       [0. , 1. ],
       [0.8, 0.2],
       [0.8, 0.2],
       [1. , 0. ],
       [0. , 1. ],
       [0.6, 0.4],
       [0. , 1. ],
       [0.6, 0.4],
       [1. , 0. ],
       [0.4, 0.6],
       [0.8, 0.2],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0.6, 0.4],
       [1. , 0. ],
       [0.4, 0.6],
       [0.4, 0.6],
       [0. , 1. ],
       [0. , 1. ],
       [0.4, 0.6],
       [1. , 0. ],
       [0.8, 0.2],
       [0.6, 0.4],
       [0.4, 0.6],
       [0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [0.6, 0.4],
       [0. , 1. ],
       [0.4,

In [21]:
y_val_pred_probaKNN[:, 1] ## predict_proba는 각 클래스의 확률을 보여줌
## 여기서 레이블은 0, 1이니깐 isUSA가 1일 확률을 가져와야 하므로 [:, 1]이라고 해줌

array([0. , 1. , 0.2, 0.2, 1. , 0.2, 0.4, 0.2, 0. , 0.4, 1. , 1. , 1. ,
       1. , 0.2, 1. , 0.2, 1. , 0.4, 0. , 1. , 0.2, 0.2, 0. , 1. , 0.4,
       1. , 0.4, 0. , 0.6, 0.2, 1. , 1. , 1. , 1. , 0.4, 0. , 0.6, 0.6,
       1. , 1. , 0.6, 0. , 0.2, 0.4, 0.6, 1. , 1. , 0. , 0. , 0.4, 1. ,
       0.6, 1. , 1. , 1. , 1. , 0.2, 0.4, 1. , 1. , 0. , 1. , 0.8, 1. ,
       0.2, 0.2, 1. , 1. , 0.4, 1. , 1. , 0.2, 1. , 0.4, 0.4, 1. , 1. ,
       1. , 0.6, 0. , 0.2, 1. , 1. ])

In [23]:
## 모델 성능 평가
from sklearn.metrics import roc_auc_score
scoreKNN = roc_auc_score(y_val, y_val_pred_probaKNN[:, 1])
scoreDT = roc_auc_score(y_val, y_val_pred_probaDT[:, 1])

In [24]:
scoreKNN, scoreDT

(0.9090079123554473, 0.8627510651247718)

In [26]:
## 하이퍼 파라미터 학습
best_model = None
best_score = 0

for i in range(2,10):
  model = KNeighborsClassifier(n_neighbors=i, metric='euclidean')
  model.fit(X_tr, y_tr.values.ravel())
  y_val_pred_proba = model.predict_proba(X_val)
  score = roc_auc_score(y_val, y_val_pred_proba[:, 1])
  print(i, "개의 이웃 확인 : ", score)
  if best_score <= score:
    best_model = model

2 개의 이웃 확인 :  0.8682288496652466
3 개의 이웃 확인 :  0.8913572732805843
4 개의 이웃 확인 :  0.8962264150943398
5 개의 이웃 확인 :  0.9090079123554473
6 개의 이웃 확인 :  0.911442483262325
7 개의 이웃 확인 :  0.9068776628119295
8 개의 이웃 확인 :  0.9108338405356056
9 개의 이웃 확인 :  0.9184418746195984


In [27]:
best_model.predict_proba(X_test)

array([[0.77777778, 0.22222222],
       [0.33333333, 0.66666667],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.77777778, 0.22222222],
       [0.66666667, 0.33333333],
       [0.44444444, 0.55555556],
       [0.66666667, 0.33333333],
       [0.77777778, 0.22222222],
       [0.44444444, 0.55555556],
       [0.        , 1.        ],
       [0.33333333, 0.66666667],
       [0.        , 1.        ],
       [0.55555556, 0.44444444],
       [0.88888889, 0.11111111],
       [0.77777778, 0.22222222],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.88888889, 0.11111111],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.66666667, 0.33333333],
       [0.66666667, 0.33333333],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.55555556, 0.44444444],
       [0.

In [28]:
pred = best_model.predict_proba(X_test)[:, 1]
pred

array([0.22222222, 0.66666667, 1.        , 1.        , 0.22222222,
       0.33333333, 0.55555556, 0.33333333, 0.22222222, 0.55555556,
       1.        , 0.66666667, 1.        , 0.44444444, 0.11111111,
       0.22222222, 1.        , 1.        , 0.11111111, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.33333333, 0.33333333, 1.        , 1.        , 0.44444444,
       0.11111111, 0.        , 0.44444444, 0.77777778, 1.        ,
       0.66666667, 0.66666667, 1.        , 0.33333333, 0.77777778,
       1.        , 0.11111111, 0.11111111, 0.44444444, 0.22222222,
       0.22222222, 0.44444444, 1.        , 0.33333333, 1.        ,
       0.11111111, 0.22222222, 1.        , 0.11111111, 1.        ,
       1.        , 1.        , 0.77777778, 1.        , 0.33333333,
       1.        , 0.66666667, 1.        , 1.        , 0.88888889,
       1.        , 1.        , 0.33333333, 0.77777778, 0.22222222,
       0.88888889, 1.        , 0.44444444, 0.11111111, 1.     

In [29]:
result_df = pd.DataFrame({'isUSA':pred})
result_df

isUSA
0    0.222222
1    0.666667
2    1.000000
3    1.000000
4    0.222222
..        ...
115  0.000000
116  1.000000
117  1.000000
118  1.000000
119  0.000000

[120 rows x 1 columns]

In [ ]:
## index=False 해서 to_csv로 결과 csv 저장